import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from flask import Flask, render_template, request, flash

app = Flask(__name__)


def send_email(name, email, subject, user_message):
    sender = 'hundreddayscode@gmail.com'
    receiver = 'rushikeshpabalkar09@gmail.com'
    password = "nxpiqeokbgstwged"
    # (generated by App Password in google security settings for sender email)

    mail_content = f"You get this response from your portfolio website.\n" \
                   f"Name: {name}\n" \
                   f"Email: {email}\n" \
                   f"Message: {user_message}"

    message = MIMEMultipart()
    message["From"] = sender
    message["To"] = receiver
    message["Subject"] = subject

    message.attach(MIMEText(mail_content, "plain"))

    session = smtplib.SMTP("smtp.gmail.com", 587)
    session.starttls()
    session.login(sender, password)
    text = message.as_string()
    session.sendmail(sender, receiver, text)
    session.quit()
    print("Successfully sent email")


@app.route("/", methods=["GET", "POST"])
def home():
    if request.method == "POST":
        try:
            send_email(request.form['name'], request.form['email'], request.form['subject'], request.form['message'])
        except RuntimeError:
            flash("Email not sent! please try again.")

    return render_template('index.html')


if __name__ == "__main__":
    app.run(debug=True)
